export declare const INJECTION_TOKENS: {
    readonly APPOINTMENT_REPOSITORY: "APPOINTMENT_REPOSITORY";
    readonly PATIENT_REPOSITORY: "PATIENT_REPOSITORY";
    readonly PSYCHOLOGIST_REPOSITORY: "PSYCHOLOGIST_REPOSITORY";
    readonly MESSAGE_QUEUE: "MESSAGE_QUEUE";
    readonly ENTERPRISE_MESSAGE_QUEUE: "ENTERPRISE_MESSAGE_QUEUE";
};
