import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<{
        development: "development";
        production: "production";
        test: "test";
    }>>;
    PORT: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    DATABASE_URL: z.ZodString;
    AWS_REGION: z.ZodDefault<z.ZodString>;
    AWS_ACCESS_KEY_ID: z.ZodOptional<z.ZodString>;
    AWS_SECRET_ACCESS_KEY: z.ZodOptional<z.ZodString>;
    AWS_ENDPOINT_URL: z.ZodOptional<z.ZodString>;
    SQS_APPOINTMENT_QUEUE_URL: z.ZodString;
    SQS_APPOINTMENT_DLQ_URL: z.ZodOptional<z.ZodString>;
    REDIS_HOST: z.ZodDefault<z.ZodString>;
    REDIS_PORT: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    REDIS_PASSWORD: z.ZodOptional<z.ZodString>;
    CORS_ORIGIN: z.ZodDefault<z.ZodString>;
    RATE_LIMIT_TTL: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    RATE_LIMIT_MAX: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    SQS_VISIBILITY_TIMEOUT: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    SQS_BATCH_SIZE: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    SQS_WAIT_TIME: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    SQS_MAX_RECEIVE_COUNT: z.ZodDefault<z.ZodCoercedNumber<unknown>>;
    OTEL_EXPORTER_OTLP_ENDPOINT: z.ZodOptional<z.ZodString>;
    CORRELATION_ID_HEADER: z.ZodDefault<z.ZodString>;
}, z.core.$strip>;
export type EnvConfig = z.infer<typeof envSchema>;
export declare function validateEnv(): EnvConfig;
export declare const env: {
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    DATABASE_URL: string;
    AWS_REGION: string;
    SQS_APPOINTMENT_QUEUE_URL: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    CORS_ORIGIN: string;
    RATE_LIMIT_TTL: number;
    RATE_LIMIT_MAX: number;
    SQS_VISIBILITY_TIMEOUT: number;
    SQS_BATCH_SIZE: number;
    SQS_WAIT_TIME: number;
    SQS_MAX_RECEIVE_COUNT: number;
    CORRELATION_ID_HEADER: string;
    AWS_ACCESS_KEY_ID?: string | undefined;
    AWS_SECRET_ACCESS_KEY?: string | undefined;
    AWS_ENDPOINT_URL?: string | undefined;
    SQS_APPOINTMENT_DLQ_URL?: string | undefined;
    REDIS_PASSWORD?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
};
export {};
