export const INJECTION_TOKENS = {
  APPOINTMENT_REPOSITORY: 'APPOINTMENT_REPOSITORY',
  PATIENT_REPOSITORY: 'PATIENT_REPOSITORY',
  PSYCHOLOGIST_REPOSITORY: 'PSYCHOLOGIST_REPOSITORY',
  MESSAGE_QUEUE: 'MESSAGE_QUEUE',
  ENTERPRISE_MESSAGE_QUEUE: 'ENTERPRISE_MESSAGE_QUEUE',
} as const;