export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  DECLINED = 'DECLINED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED',
}

export enum AppointmentType {
  CONSULTATION = 'CONSULTATION',
  FOLLOW_UP = 'FOLLOW_UP',
  THERAPY_SESSION = 'THERAPY_SESSION',
  ASSESSMENT = 'ASSESSMENT',
  GROUP_SESSION = 'GROUP_SESSION',
  EMERGENCY = 'EMERGENCY',
}

export enum MeetingType {
  IN_PERSON = 'IN_PERSON',
  ONLINE = 'ONLINE', // Added ONLINE for backward compatibility
  VIDEO_CALL = 'VIDEO_CALL',
  PHONE_CALL = 'PHONE_CALL',
  HYBRID = 'HYBRID',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER', // For Prisma compatibility
  NON_BINARY = 'NON_BINARY',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}
